---
title: "Projects"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# Plotly

We are making interactive plots

```{r}
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  select(borough = neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) |> 
  drop_na(stars) |> 
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

## Make a scatterplot!

```{r}
nyc_airbnb |> 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", stars)) |> #\n: line break
  plot_ly(x = ~lat, y = ~long, color = ~price, text = ~text_label,
          type = "scatter", mode = "markers")
```

## Make a boxplot!

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, 
          type = "box")
```

## Make a barplot!

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood,
          type = "bar", colors = "viridis")
```

# ggplotly

ggplot scatterplot
```{r}
ggp_scatter = nyc_airbnb |> 
  ggplot(aes(x=lat, y=long, color = price))+
  geom_point(alpha = 0.5)

#ggplotly(ggp_scatter)
```
